# Imports

In [ ]:
import pandas as pd
import numpy as np

# Read data

## IMPORTANT: you need to upload tthe 'tweets_ws22_v1.json' file into your Colab environment using the left sidebar in order for the code to work

In [ ]:


tweets = pd.read_json('tweets_ws22_v1.json',dtype={'source_created_at': pd.Timestamp,'author_id': str, 'source_id': str})
tweets
# relevant, ground_truth, user_id all useless
# topic: 
#       delays 9023
#       doors  197
#       air conditioning 252
#       announcements 315
#       brakes 44
#       covid 375
#       floor 45
#       hvac 172
#       handrails 2
#       none 2304
#       noise 77
#       plugs 135
#       roof 15
#       service 884
#       seats 283
#       station 754
#       toilets 282
#       tables 189
#       tickets/seat_reservations 273
#       train_general 385
#       vandalism 273
#       wifi 620
#       windows 50

,source_created_at,author_id,text,source,language,longitude,latitude,id,labels,source_id
0,2020-09-18 21:56:20.798000,593731316,@DSisourath The Thameslink core between London...,sprinklr,en,-0.12574,51.50853,acd7673f-e621-5f1a-d662-df278964a6ea,{'topic': [{'tweet_id': 'acd7673f-e621-5f1a-d6...,nan
1,2020-10-13 07:31:53.122000,745583289520496640,@DulwichHistory Loving the complaint about peo...,sprinklr,en,-0.12574,51.50853,5b92aba8-4b05-6c63-8485-e9c870742137,{'topic': [{'tweet_id': '5b92aba8-4b05-6c63-84...,nan
2,2020-10-26 19:27:24.695000,303134761,@SW_Help .And yet you have no toilets on some ...,sprinklr,en,-0.12574,51.50853,0a799c07-8b76-17ba-b840-e538d51e832d,{'topic': [{'tweet_id': '0a799c07-8b76-17ba-b8...,nan
3,2020-10-26 19:28:49.281000,303134761,@SW_Help you have no toilets on some of your t...,sprinklr,en,-0.12574,51.50853,8b4d2a34-c4f0-0e19-4055-dfe4af5f0e14,{'topic': [{'tweet_id': '8b4d2a34-c4f0-0e19-40...,nan
4,2020-09-28 11:59:41.212000,56427671,@SpeedySticks007 @MrNeilJH @TLRailUK @christia...,sprinklr,en,-1.09125,50.79899,1fd08862-d8c7-0682-6b11-2603fba22d94,{'topic': [{'tweet_id': '1fd08862-d8c7-0682-6b...,nan
...,...,...,...,...,...,...,...,...,...,...
16944,2019-07-11 07:34:35,24940900,Haha oh man the audio corruption on @TLRailUK ...,brandwatch,en-GB,NaN,NaN,b47948df-1732-7021-ee77-238f839a2ea0,{'topic': [{'tweet_id': 'b47948df-1732-7021-ee...,1149220424313708544
16945,2020-08-10 11:19:10.181000,63559912,@TLRailUK SweetIs there a plug to charge my ph...,sprinklr,en,-0.12574,51.50853,bcb3a01a-e58c-e082-3111-10fa77d1a9f7,{'topic': [{'tweet_id': 'bcb3a01a-e58c-e082-31...,nan
16946,2020-08-29 09:51:10.833000,277455263,@TLRailUK now there are far fewer commuters ha...,sprinklr,en,-0.12574,51.50853,f440c7e6-9e2d-31c4-3626-b9d8288cbbe3,{'topic': [{'tweet_id': 'f440c7e6-9e2d-31c4-36...,nan
16947,2020-11-02 12:06:06.967000,3050957613,@geofftech I am voting for Thameslink. 1. in a...,sprinklr,en,-0.12574,51.50853,859ab156-cad3-3bf0-4b6d-de494b483501,{'topic': [{'tweet_id': '859ab156-cad3-3bf0-4b...,nan
16948,2020-11-02 12:06:06.967000,3050957613,@geofftech I am voting for Thameslink. 1. in a...,sprinklr,en,-0.12574,51.50853,859ab156-cad3-3bf0-4b6d-de494b483501,{'topic': [{'tweet_id': '859ab156-cad3-3bf0-4b...,nan

In [ ]:
tweets.dtypes

source_created_at     object
author_id             object
text                  object
source                object
language              object
longitude            float64
latitude             float64
id                    object
labels                object
source_id             object
dtype: object

In [ ]:
tweets['source'].value_counts()

brandwatch    15548
sprinklr       1401
Name: source, dtype: int64

In [ ]:
# List of authors with >10 tweets
tweets['author_id'] = tweets['author_id'].str.replace(".0","", regex=False)
tweets['author_id'].value_counts().loc[lambda x: x>10]

2589703207               1173
963564801195741184        496
9.635648011957412e+17     294
1099408261781032960       283
1143420803549151232       247
                         ...
320654965                  11
97070364                   11
1994082617810328e+18       11
763881199                  11
2160745083                 11
Name: author_id, Length: 123, dtype: int64

In [ ]:
print("Earliest tweet: ", tweets['source_created_at'].min())
print("Latest tweet:   ", tweets['source_created_at'].max())

Earliest tweet:  2019-01-16 10:41:46
Latest tweet:    2020-12-01 07:49:12.003000

In [ ]:
labels = pd.json_normalize(tweets['labels'])
labels

,topic,sentiment
0,[{'tweet_id': 'acd7673f-e621-5f1a-d662-df27896...,[{'tweet_id': 'acd7673f-e621-5f1a-d662-df27896...
1,[{'tweet_id': '5b92aba8-4b05-6c63-8485-e9c8707...,[{'tweet_id': '5b92aba8-4b05-6c63-8485-e9c8707...
2,[{'tweet_id': '0a799c07-8b76-17ba-b840-e538d51...,[{'tweet_id': '0a799c07-8b76-17ba-b840-e538d51...
3,[{'tweet_id': '8b4d2a34-c4f0-0e19-4055-dfe4af5...,[{'tweet_id': '8b4d2a34-c4f0-0e19-4055-dfe4af5...
4,[{'tweet_id': '1fd08862-d8c7-0682-6b11-2603fba...,[{'tweet_id': '1fd08862-d8c7-0682-6b11-2603fba...
...,...,...
16944,[{'tweet_id': 'b47948df-1732-7021-ee77-238f839...,[{'tweet_id': 'b47948df-1732-7021-ee77-238f839...
16945,[{'tweet_id': 'bcb3a01a-e58c-e082-3111-10fa77d...,[{'tweet_id': 'bcb3a01a-e58c-e082-3111-10fa77d...
16946,[{'tweet_id': 'f440c7e6-9e2d-31c4-3626-b9d8288...,[{'tweet_id': 'f440c7e6-9e2d-31c4-3626-b9d8288...
16947,[{'tweet_id': '859ab156-cad3-3bf0-4b6d-de494b4...,[{'tweet_id': '859ab156-cad3-3bf0-4b6d-de494b4...
16948,[{'tweet_id': '859ab156-cad3-3bf0-4b6d-de494b4...,[{'tweet_id': '859ab156-cad3-3bf0-4b6d-de494b4...

In [ ]:
tweets[tweets['text'].str.contains('Thameslink')]

,source_created_at,author_id,text,source,language,longitude,latitude,id,labels,source_id
0,2020-09-18 21:56:20.798000,593731316,@DSisourath The Thameslink core between London...,sprinklr,en,-0.12574,51.50853,acd7673f-e621-5f1a-d662-df278964a6ea,{'topic': [{'tweet_id': 'acd7673f-e621-5f1a-d6...,nan
1,2020-10-13 07:31:53.122000,745583289520496640,@DulwichHistory Loving the complaint about peo...,sprinklr,en,-0.12574,51.50853,5b92aba8-4b05-6c63-8485-e9c870742137,{'topic': [{'tweet_id': '5b92aba8-4b05-6c63-84...,nan
7,2020-09-04 19:01:37.077000,48791087,@TLRailUK On the Bedford to Brighton route - w...,sprinklr,en,-0.12574,51.50853,27258e21-23cb-479f-a31a-9dd20d2a8c7c,{'topic': [{'tweet_id': '27258e21-23cb-479f-a3...,nan
12,2020-10-27 19:25:36.303000,1246510629059465219,"Funnily enough, around a year ago I was return...",sprinklr,en,-0.12574,51.50853,e3b960eb-fe94-8c07-0a24-3ee454df02da,{'topic': [{'tweet_id': 'e3b960eb-fe94-8c07-0a...,nan
13,2020-08-14 13:10:45.785000,2341951214,Govia Thameslink #Railway station information ...,sprinklr,en,-1.46590,53.38297,cb17dc8c-425e-be96-8251-083ed003d2e0,{'topic': [{'tweet_id': 'cb17dc8c-425e-be96-82...,nan
...,...,...,...,...,...,...,...,...,...,...
16939,2020-11-03 09:17:40.252000,755518189090512896,@geofftech ThameslinkA) it’s the underdogB) 12...,sprinklr,en,-0.70312,52.16045,e63a84f2-1836-5a85-2770-7c7b638a3c35,{'topic': [{'tweet_id': 'e63a84f2-1836-5a85-27...,nan
16940,2020-10-26 09:10:26.785000,623824593,@geofftech Thameslink is taking the piss.Quite...,sprinklr,en,-0.12574,51.50853,35ac9bc5-4578-17ba-72be-1d156996d44c,{'topic': [{'tweet_id': '35ac9bc5-4578-17ba-72...,nan
16943,2019-07-11 15:06:42,759412872472588288,At St. Alban's City has the PIS Screen firmwar...,brandwatch,en-GB,NaN,NaN,6f429a04-5817-f054-24d0-a9f20fddeb25,{'topic': [{'tweet_id': '6f429a04-5817-f054-24...,1149334205945585665
16947,2020-11-02 12:06:06.967000,3050957613,@geofftech I am voting for Thameslink. 1. in a...,sprinklr,en,-0.12574,51.50853,859ab156-cad3-3bf0-4b6d-de494b483501,{'topic': [{'tweet_id': '859ab156-cad3-3bf0-4b...,nan
16948,2020-11-02 12:06:06.967000,3050957613,@geofftech I am voting for Thameslink. 1. in a...,sprinklr,en,-0.12574,51.50853,859ab156-cad3-3bf0-4b6d-de494b483501,{'topic': [{'tweet_id': '859ab156-cad3-3bf0-4b...,nan